"""Initial migration

Revision ID: 7887f4076b0a
Revises: 
Create Date: 2026-09-16 19:33:32.913367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7887f4076b0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_id', sa.String(), nullable=True),
    sa.Column('reading_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('challenge_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('used_explain', sa.Boolean(), nullable=True),
    sa.Column('reread_count', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_attempts_id'), 'challenge_attempts', ['id'], unique=False)
    op.create_table('learner_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('vocabulary', sa.Float(), nullable=True),
    sa.Column('literal_comprehension', sa.Float(), nullable=True),
    sa.Column('inference', sa.Float(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('evidence_finding', sa.Float(), nullable=True),
    sa.Column('reading_fluency', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_learner_models_id'), 'learner_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_models_id'), table_name='learner_models')
    op.drop_table('learner_models')
    op.drop_index(op.f('ix_challenge_attempts_id'), table_name='challenge_attempts')
    op.drop_table('challenge_attempts')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
