"""add_story_models

Revision ID: 7b4b132b745e
Revises: d9a7394235d4
Create Date: 2026-09-17 13:58:27.362335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4b132b745e'
down_revision: Union[str, Sequence[str], None] = 'd9a7394235d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_sessions_id'), 'story_sessions', ['id'], unique=False)
    op.create_table('story_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('passage_text', sa.String(), nullable=False),
    sa.Column('vocabulary_words', sa.JSON(), nullable=False),
    sa.Column('target_lexile', sa.Integer(), nullable=False),
    sa.Column('focus_skill', sa.String(), nullable=False),
    sa.Column('parent_node_id', sa.String(), nullable=True),
    sa.Column('choice_made', sa.String(), nullable=True),
    sa.Column('branch_choices', sa.JSON(), nullable=True),
    sa.Column('challenge_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_node_id'], ['story_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_nodes_id'), 'story_nodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_nodes_id'), table_name='story_nodes')
    op.drop_table('story_nodes')
    op.drop_index(op.f('ix_story_sessions_id'), table_name='story_sessions')
    op.drop_table('story_sessions')
    # ### end Alembic commands ###
