"""add_adaptive_metrics

Revision ID: d9a7394235d4
Revises: 7887f4076b0a
Create Date: 2026-09-17 13:57:03.622968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a7394235d4'
down_revision: Union[str, Sequence[str], None] = '7887f4076b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_models', sa.Column('current_lexile', sa.Integer(), nullable=True))
    op.add_column('learner_models', sa.Column('total_words_read', sa.Integer(), nullable=True))
    op.add_column('learner_models', sa.Column('total_sessions', sa.Integer(), nullable=True))
    op.add_column('learner_models', sa.Column('current_streak_days', sa.Integer(), nullable=True))
    op.add_column('learner_models', sa.Column('longest_streak_days', sa.Integer(), nullable=True))
    op.add_column('learner_models', sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_models', 'last_session_at')
    op.drop_column('learner_models', 'longest_streak_days')
    op.drop_column('learner_models', 'current_streak_days')
    op.drop_column('learner_models', 'total_sessions')
    op.drop_column('learner_models', 'total_words_read')
    op.drop_column('learner_models', 'current_lexile')
    # ### end Alembic commands ###
